// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: internal/grpc/proto/ping.proto

package contract

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PingHandler_CheckStorageConnect_FullMethodName = "/contract.PingHandler/CheckStorageConnect"
)

// PingHandlerClient is the client API for PingHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PingHandlerClient interface {
	CheckStorageConnect(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CheckStorageConnectResponse, error)
}

type pingHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewPingHandlerClient(cc grpc.ClientConnInterface) PingHandlerClient {
	return &pingHandlerClient{cc}
}

func (c *pingHandlerClient) CheckStorageConnect(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CheckStorageConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckStorageConnectResponse)
	err := c.cc.Invoke(ctx, PingHandler_CheckStorageConnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PingHandlerServer is the server API for PingHandler service.
// All implementations must embed UnimplementedPingHandlerServer
// for forward compatibility.
type PingHandlerServer interface {
	CheckStorageConnect(context.Context, *empty.Empty) (*CheckStorageConnectResponse, error)
	mustEmbedUnimplementedPingHandlerServer()
}

// UnimplementedPingHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPingHandlerServer struct{}

func (UnimplementedPingHandlerServer) CheckStorageConnect(context.Context, *empty.Empty) (*CheckStorageConnectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckStorageConnect not implemented")
}
func (UnimplementedPingHandlerServer) mustEmbedUnimplementedPingHandlerServer() {}
func (UnimplementedPingHandlerServer) testEmbeddedByValue()                     {}

// UnsafePingHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PingHandlerServer will
// result in compilation errors.
type UnsafePingHandlerServer interface {
	mustEmbedUnimplementedPingHandlerServer()
}

func RegisterPingHandlerServer(s grpc.ServiceRegistrar, srv PingHandlerServer) {
	// If the following call pancis, it indicates UnimplementedPingHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PingHandler_ServiceDesc, srv)
}

func _PingHandler_CheckStorageConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingHandlerServer).CheckStorageConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PingHandler_CheckStorageConnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingHandlerServer).CheckStorageConnect(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PingHandler_ServiceDesc is the grpc.ServiceDesc for PingHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PingHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "contract.PingHandler",
	HandlerType: (*PingHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckStorageConnect",
			Handler:    _PingHandler_CheckStorageConnect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/grpc/proto/ping.proto",
}
