// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.12.4
// source: internal/grpc/proto/shortener.proto

package contract

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortenerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *ShortenerRequest) Reset() {
	*x = ShortenerRequest{}
	mi := &file_internal_grpc_proto_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenerRequest) ProtoMessage() {}

func (x *ShortenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenerRequest.ProtoReflect.Descriptor instead.
func (*ShortenerRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenerRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ShortenerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *ShortenerResponse) Reset() {
	*x = ShortenerResponse{}
	mi := &file_internal_grpc_proto_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenerResponse) ProtoMessage() {}

func (x *ShortenerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenerResponse.ProtoReflect.Descriptor instead.
func (*ShortenerResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenerResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type ShortenerJSONRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *ShortenerJSONRequest) Reset() {
	*x = ShortenerJSONRequest{}
	mi := &file_internal_grpc_proto_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenerJSONRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenerJSONRequest) ProtoMessage() {}

func (x *ShortenerJSONRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenerJSONRequest.ProtoReflect.Descriptor instead.
func (*ShortenerJSONRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *ShortenerJSONRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ShortenerJSONResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ShortenerJSONResponse) Reset() {
	*x = ShortenerJSONResponse{}
	mi := &file_internal_grpc_proto_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenerJSONResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenerJSONResponse) ProtoMessage() {}

func (x *ShortenerJSONResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenerJSONResponse.ProtoReflect.Descriptor instead.
func (*ShortenerJSONResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *ShortenerJSONResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ShortenerBatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ShortenerBatchRequest_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ShortenerBatchRequest) Reset() {
	*x = ShortenerBatchRequest{}
	mi := &file_internal_grpc_proto_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenerBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenerBatchRequest) ProtoMessage() {}

func (x *ShortenerBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenerBatchRequest.ProtoReflect.Descriptor instead.
func (*ShortenerBatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *ShortenerBatchRequest) GetItems() []*ShortenerBatchRequest_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ShortenerBatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ShortenerBatchResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ShortenerBatchResponse) Reset() {
	*x = ShortenerBatchResponse{}
	mi := &file_internal_grpc_proto_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenerBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenerBatchResponse) ProtoMessage() {}

func (x *ShortenerBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenerBatchResponse.ProtoReflect.Descriptor instead.
func (*ShortenerBatchResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *ShortenerBatchResponse) GetItems() []*ShortenerBatchResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ShortenerBatchRequest_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
}

func (x *ShortenerBatchRequest_Item) Reset() {
	*x = ShortenerBatchRequest_Item{}
	mi := &file_internal_grpc_proto_shortener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenerBatchRequest_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenerBatchRequest_Item) ProtoMessage() {}

func (x *ShortenerBatchRequest_Item) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_shortener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenerBatchRequest_Item.ProtoReflect.Descriptor instead.
func (*ShortenerBatchRequest_Item) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_shortener_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ShortenerBatchRequest_Item) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ShortenerBatchRequest_Item) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type ShortenerBatchResponse_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ShortUrl      string `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *ShortenerBatchResponse_Item) Reset() {
	*x = ShortenerBatchResponse_Item{}
	mi := &file_internal_grpc_proto_shortener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenerBatchResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenerBatchResponse_Item) ProtoMessage() {}

func (x *ShortenerBatchResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_shortener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenerBatchResponse_Item.ProtoReflect.Descriptor instead.
func (*ShortenerBatchResponse_Item) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_shortener_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ShortenerBatchResponse_Item) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ShortenerBatchResponse_Item) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

var File_internal_grpc_proto_shortener_proto protoreflect.FileDescriptor

var file_internal_grpc_proto_shortener_proto_rawDesc = []byte{
	0x0a, 0x23, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x22,
	0x24, 0x0a, 0x10, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x30, 0x0a, 0x11, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x28, 0x0a, 0x14, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x65, 0x6e, 0x65, 0x72, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x22, 0x2f, 0x0a, 0x15, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x4a, 0x53,
	0x4f, 0x4e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0xa5, 0x01, 0x0a, 0x15, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x50, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55, 0x72, 0x6c, 0x22, 0xa1, 0x01, 0x0a, 0x16, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x1a, 0x4a, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f,
	0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x32, 0xff,
	0x01, 0x0a, 0x10, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x48, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x72, 0x12, 0x44, 0x0a, 0x09, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72,
	0x12, 0x1a, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x65, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0d, 0x53, 0x68, 0x6f,
	0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x4a, 0x53, 0x4f, 0x4e, 0x12, 0x1e, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x4a,
	0x53, 0x4f, 0x4e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x4a,
	0x53, 0x4f, 0x4e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x0e, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1f, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e,
	0x65, 0x72, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20,
	0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x6e, 0x65, 0x72, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x0b, 0x5a, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_grpc_proto_shortener_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_shortener_proto_rawDescData = file_internal_grpc_proto_shortener_proto_rawDesc
)

func file_internal_grpc_proto_shortener_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_shortener_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_grpc_proto_shortener_proto_rawDescData)
	})
	return file_internal_grpc_proto_shortener_proto_rawDescData
}

var file_internal_grpc_proto_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_grpc_proto_shortener_proto_goTypes = []any{
	(*ShortenerRequest)(nil),            // 0: contract.ShortenerRequest
	(*ShortenerResponse)(nil),           // 1: contract.ShortenerResponse
	(*ShortenerJSONRequest)(nil),        // 2: contract.ShortenerJSONRequest
	(*ShortenerJSONResponse)(nil),       // 3: contract.ShortenerJSONResponse
	(*ShortenerBatchRequest)(nil),       // 4: contract.ShortenerBatchRequest
	(*ShortenerBatchResponse)(nil),      // 5: contract.ShortenerBatchResponse
	(*ShortenerBatchRequest_Item)(nil),  // 6: contract.ShortenerBatchRequest.Item
	(*ShortenerBatchResponse_Item)(nil), // 7: contract.ShortenerBatchResponse.Item
}
var file_internal_grpc_proto_shortener_proto_depIdxs = []int32{
	6, // 0: contract.ShortenerBatchRequest.items:type_name -> contract.ShortenerBatchRequest.Item
	7, // 1: contract.ShortenerBatchResponse.items:type_name -> contract.ShortenerBatchResponse.Item
	0, // 2: contract.ShortenerHandler.Shortener:input_type -> contract.ShortenerRequest
	2, // 3: contract.ShortenerHandler.ShortenerJSON:input_type -> contract.ShortenerJSONRequest
	4, // 4: contract.ShortenerHandler.ShortenerBatch:input_type -> contract.ShortenerBatchRequest
	1, // 5: contract.ShortenerHandler.Shortener:output_type -> contract.ShortenerResponse
	3, // 6: contract.ShortenerHandler.ShortenerJSON:output_type -> contract.ShortenerJSONResponse
	5, // 7: contract.ShortenerHandler.ShortenerBatch:output_type -> contract.ShortenerBatchResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_shortener_proto_init() }
func file_internal_grpc_proto_shortener_proto_init() {
	if File_internal_grpc_proto_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_grpc_proto_shortener_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_proto_shortener_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_shortener_proto_depIdxs,
		MessageInfos:      file_internal_grpc_proto_shortener_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_shortener_proto = out.File
	file_internal_grpc_proto_shortener_proto_rawDesc = nil
	file_internal_grpc_proto_shortener_proto_goTypes = nil
	file_internal_grpc_proto_shortener_proto_depIdxs = nil
}
