// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: internal/grpc/proto/stats.proto

package contract

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StatsHandler_Stats_FullMethodName = "/contract.StatsHandler/Stats"
)

// StatsHandlerClient is the client API for StatsHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatsHandlerClient interface {
	Stats(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StatsResponse, error)
}

type statsHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewStatsHandlerClient(cc grpc.ClientConnInterface) StatsHandlerClient {
	return &statsHandlerClient{cc}
}

func (c *statsHandlerClient) Stats(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, StatsHandler_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatsHandlerServer is the server API for StatsHandler service.
// All implementations must embed UnimplementedStatsHandlerServer
// for forward compatibility.
type StatsHandlerServer interface {
	Stats(context.Context, *empty.Empty) (*StatsResponse, error)
	mustEmbedUnimplementedStatsHandlerServer()
}

// UnimplementedStatsHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStatsHandlerServer struct{}

func (UnimplementedStatsHandlerServer) Stats(context.Context, *empty.Empty) (*StatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedStatsHandlerServer) mustEmbedUnimplementedStatsHandlerServer() {}
func (UnimplementedStatsHandlerServer) testEmbeddedByValue()                      {}

// UnsafeStatsHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatsHandlerServer will
// result in compilation errors.
type UnsafeStatsHandlerServer interface {
	mustEmbedUnimplementedStatsHandlerServer()
}

func RegisterStatsHandlerServer(s grpc.ServiceRegistrar, srv StatsHandlerServer) {
	// If the following call pancis, it indicates UnimplementedStatsHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StatsHandler_ServiceDesc, srv)
}

func _StatsHandler_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsHandlerServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsHandler_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsHandlerServer).Stats(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// StatsHandler_ServiceDesc is the grpc.ServiceDesc for StatsHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatsHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "contract.StatsHandler",
	HandlerType: (*StatsHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stats",
			Handler:    _StatsHandler_Stats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/grpc/proto/stats.proto",
}
