profile: cover.out
local-prefix: "github.com/northmule/shorturl"

# Holds coverage thresholds percentages, values should be in range [0-100]
threshold:
  # (optional; default 0)
  # The minimum coverage that each file should have
  file: 0

  # (optional; default 0)
  # The minimum coverage that each package should have
  package: 0

  # (optional; default 0)
  # The minimum total coverage project should have
  total: 70


# Holds regexp rules which will exclude matched files or packages
# from coverage statistics
exclude:
  # Exclude files or packages matching their paths
  paths:
    - \.pb\.go$    # excludes all protobuf generated files
    - ^internal/app/storage/mocks/*
    - ^cmd/*
    - ^profiles/*
    - ^tools/*
    - ^internal/linter/testdata/*
    - ^db/*
    - ^internal/app/storage/mocks/*
    - ^internal/app/storage/models/*
